import 'reflect-metadata';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes,randomUUID } from 'node:crypto';
import { parse } from 'dotenv';
import { JwtService } from '@nestjs/jwt';
import { NestFactory } from '@nestjs/core';
import sharp from 'sharp';
import { PrismaService } from '../src/database/prisma.service.js';
import { AppModule } from '../src/app.module.js';
import { configureApp } from '../src/common/configure-app.js';
import { AccessService } from '../src/common/access.service.js';
import { DishService } from '../src/dish/dish.service.js';
const env=parse(readFileSync(process.argv[2])),url=new URL(env.DATABASE_URL);
if(url.hostname!=='127.0.0.1'||url.port!=='3317'||url.pathname!=='/family_meals_base_test')throw new Error('Refusing non-isolated DB');
process.env.DATABASE_URL=env.DATABASE_URL;
process.env.JWT_SECRET=randomBytes(48).toString('base64');
process.env.IDEMPOTENCY_ENCRYPTION_KEY=randomBytes(32).toString('base64');
process.env.FILE_SIGNING_KEY=randomBytes(48).toString('base64');
const run=randomUUID();process.env.FILE_STORAGE_ROOT=resolve('.local','test-assets',run);
const app=await NestFactory.create(AppModule,{logger:false});await configureApp(app);
const db=app.get(PrismaService),jwt=new JwtService();let checked=0;
try{
 await app.listen(0,'127.0.0.1');const base=await app.getUrl();process.env.FILE_PUBLIC_BASE_URL=base;
 const users=await Promise.all(Array.from({length:6},(_,i)=>db.user.create({data:{wechatAppId:run,openid:'test-user-'+i,displayName:'测试成员'+i}})));
 const tokens=await Promise.all(users.map(u=>jwt.signAsync({sub:u.id},{secret:process.env.JWT_SECRET,expiresIn:7200,algorithm:'HS256'})));
 async function request(user:number,method:string,path:string,body:unknown,status=200,key=randomUUID(),code?:string){
  const response=await fetch(base+'/api/v1'+path,{method,headers:{authorization:'Bearer '+tokens[user],'idempotency-key':key,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});
  const payload=await response.json();assert.equal(response.status,status,method+' '+path+' '+JSON.stringify(payload));assert.ok(payload.requestId);if(code)assert.equal(payload.error.code,code);checked++;return payload.data;
 }
 const bootstrap=await db.family.create({data:{name:'Test bootstrap '+run}});
 for(const i of [0,4])await db.familyMember.create({data:{familyId:bootstrap.id,userId:users[i].id,role:'ADMIN',status:'ACTIVE',joinedAt:new Date('2000-01-01')}});
 await request(5,'POST','/families',{name:'Must not create admin'},403,randomUUID(),'FORBIDDEN');
 const family=await request(0,'POST','/families',{name:'基础回归 '+run},201);
 const f='/families/'+family.id,admin=f+'/admin';
 process.env.REGISTRATION_FAMILY_ID=family.id;
 await request(5,'GET',f+'/members',undefined,403,randomUUID(),'MEMBERSHIP_INACTIVE');
 const fixedJoined=await request(5,'POST','/invites/redeem',{code:'REPLACE_GUEST_CODE'});assert.equal(fixedJoined.family.role,'GUEST');
 assert.ok((await db.menuOperation.findFirstOrThrow({where:{familyId:family.id,action:'MEMBER_JOIN',resourceId:fixedJoined.family.memberId}})).summary.includes('测试成员5'));checked++;
 const roster=await request(5,'GET',f+'/members',undefined);assert.ok(roster.items.some((m:any)=>m.id===fixedJoined.family.memberId));
 await request(5,'GET',admin+'/members',undefined,403,randomUUID(),'FORBIDDEN');
 const expires=(await db.familyMember.findUniqueOrThrow({where:{id:fixedJoined.family.memberId}})).accessExpiresAt!;
 await request(5,'POST','/invites/redeem',{code:'REPLACE_GUEST_CODE'});
 assert.equal((await db.familyMember.findUniqueOrThrow({where:{id:fixedJoined.family.memberId}})).accessExpiresAt!.getTime(),expires.getTime());
 await db.familyMember.update({where:{id:fixedJoined.family.memberId},data:{accessExpiresAt:new Date(Date.now()-1000)}});
 await request(5,'GET',f+'/members',undefined,403,randomUUID(),'MEMBERSHIP_INACTIVE');
 await request(5,'POST','/invites/redeem',{code:'REPLACE_GUEST_CODE'},403,randomUUID(),'MEMBERSHIP_INACTIVE');
 assert.equal((await request(5,'GET','/me/families',undefined)).some((f:any)=>f.id===family.id),false);
 assert.equal((await request(0,'GET',f+'/members',undefined)).items.some((m:any)=>m.id===fixedJoined.family.memberId),false);
 assert.ok((await request(0,'GET',admin+'/members',undefined)).items.some((m:any)=>m.id===fixedJoined.family.memberId));
 const newGuest=await request(0,'POST',admin+'/invites',{role:'GUEST'},201);
 const renewed=await request(5,'POST','/invites/redeem',{code:newGuest.code});assert.ok(Date.parse(renewed.family.accessExpiresAt)>Date.now());
 await db.familyMember.update({where:{id:fixedJoined.family.memberId},data:{accessExpiresAt:new Date(Date.now()-1000)}});
 await request(5,'POST','/invites/redeem',{code:newGuest.code},403,randomUUID(),'MEMBERSHIP_INACTIVE');
 const formalInvite=await request(0,'POST',admin+'/invites',{role:'MEMBER'},201);
 const formal=await request(5,'POST','/invites/redeem',{code:formalInvite.code});assert.equal(formal.family.role,'MEMBER');assert.equal(formal.family.accessExpiresAt,null);
 await request(0,'PATCH',admin+'/members/'+fixedJoined.family.memberId,{role:'GUEST'});
 await db.familyMember.update({where:{id:fixedJoined.family.memberId},data:{accessExpiresAt:new Date(Date.now()-1000)}});
 const approved=await request(0,'PATCH',admin+'/members/'+fixedJoined.family.memberId,{role:'MEMBER'});assert.equal(approved.accessExpiresAt,null);
 await request(5,'GET',f+'/members',undefined);
 await request(5,'POST','/invites/redeem',{code:'REPLACE_LEGACY_CODE'},404,randomUUID(),'NOT_FOUND');
 process.env.REGISTRATION_ADMIN_CODE=randomBytes(32).toString('hex');
 const promotedMember=await request(5,'POST','/invites/redeem',{code:process.env.REGISTRATION_ADMIN_CODE});assert.equal(promotedMember.family.role,'ADMIN');
 delete process.env.REGISTRATION_ADMIN_CODE;
 await request(5,'GET',admin+'/members',undefined);
 const kept=await request(5,'POST','/invites/redeem',{code:'REPLACE_GUEST_CODE'});assert.equal(kept.family.role,'ADMIN');
 await request(0,'DELETE',admin+'/members/'+fixedJoined.family.memberId,undefined);
 await request(5,'POST','/invites/redeem',{code:'REPLACE_GUEST_CODE'},403,randomUUID(),'MEMBERSHIP_INACTIVE');
 assert.equal((await request(0,'GET','/me',undefined)).id,users[0].id);
 await request(0,'PATCH','/me',{displayName:'更新后的成员'});
 assert.equal((await request(0,'GET','/me/families',undefined))[0].id,family.id);
 await request(0,'DELETE',f+'/members/me',undefined,409,randomUUID(),'LAST_ADMIN');
 const key=randomUUID(),invite=await request(0,'POST',admin+'/invites',{role:'MEMBER'},201,key);
 assert.deepEqual(await request(0,'POST',admin+'/invites',{role:'MEMBER'},201,key),invite);
 await request(0,'POST',admin+'/invites',{role:'GUEST'},409,key,'IDEMPOTENCY_CONFLICT');
 const records=await db.idempotencyRecord.findMany({where:{userId:users[0].id,key}});assert.equal(records.length,1);assert.equal(Buffer.from(records[0].responseCiphertext!).includes(Buffer.from(invite.code)),false);checked++;
 const joined=await request(1,'POST','/invites/redeem',{code:invite.code});assert.equal(joined.alreadyJoined,false);
 await request(0,'DELETE',admin+'/invites/'+invite.id,undefined);
 assert.equal((await request(1,'POST','/invites/redeem',{code:invite.code})).alreadyJoined,true);
 await request(2,'POST','/invites/redeem',{code:invite.code},410,randomUUID(),'INVITE_REVOKED');
 await request(1,'GET',admin+'/members',undefined,403,randomUUID(),'FORBIDDEN');
 const selfKey=randomUUID();await request(1,'DELETE',f+'/members/me',undefined,200,selfKey);await request(1,'DELETE',f+'/members/me',undefined,200,selfKey);
 await request(1,'POST','/invites/redeem',{code:invite.code},409,randomUUID(),'INVITE_ALREADY_USED');
 const next=await request(0,'POST',admin+'/invites',{role:'MEMBER'},201);const rejoined=await request(1,'POST','/invites/redeem',{code:next.code});assert.equal(rejoined.family.memberId,joined.family.memberId);
 const guest=await request(0,'POST',admin+'/invites',{role:'GUEST'},201);await request(2,'POST','/invites/redeem',{code:guest.code});
 const expired=await request(0,'POST',admin+'/invites',{role:'GUEST'},201);await db.invite.update({where:{id:expired.id},data:{expiresAt:new Date(Date.now()-1000)}});await request(3,'POST','/invites/redeem',{code:expired.code},410,randomUUID(),'INVITE_EXPIRED');
 const dishBody={name:'鸡肉',description:'说明',imageFileId:null,isAvailable:true,variants:[{name:'原味',portionDescription:'一份两人',description:'',isAvailable:true}]};
 const dish=await request(0,'POST',admin+'/dishes',dishBody,201);
 await request(0,'POST',admin+'/dishes',dishBody,409,randomUUID(),'DUPLICATE_NAME');
 await request(0,'PATCH',admin+'/dishes/'+dish.id,{expectedVersion:9,name:'新菜'},409,randomUUID(),'VERSION_CONFLICT');
 await request(0,'DELETE',admin+'/dishes/'+dish.id+'/variants/'+dish.variants[0].id+'?expectedVersion=1',undefined,400,randomUUID(),'VALIDATION_ERROR');
 const variant=await request(0,'POST',admin+'/dishes/'+dish.id+'/variants',{name:'香辣',portionDescription:'一份',description:'',isAvailable:true},201);
 const updated=await request(0,'GET',admin+'/dishes/'+dish.id,undefined);assert.equal(updated.version,2);
 await request(0,'PATCH',admin+'/dishes/'+dish.id+'/variants/'+variant.id,{expectedVersion:1,name:'微辣'});
 await request(0,'DELETE',admin+'/dishes/'+dish.id+'/variants/'+variant.id+'?expectedVersion=2',undefined);
 const other=await request(4,'POST','/families',{name:'另一家庭 '+run},201);
 await request(4,'GET','/families/'+other.id+'/admin/dishes/'+dish.id,undefined,404,randomUUID(),'NOT_FOUND');
 await request(4,'GET',admin+'/dishes/'+dish.id,undefined,403,randomUUID(),'MEMBERSHIP_INACTIVE');
 await assert.rejects(()=>db.dishVariant.create({data:{familyId:other.id,dishId:dish.id,name:'bad',normalizedName:'bad',activeNameKey:'bad',portionDescription:'bad',isAvailable:true}}));checked++;
 const photo=await sharp({create:{width:16,height:16,channels:3,background:'#abcdef'}}).jpeg().withMetadata({exif:{IFD0:{Artist:'PRIVATE'}}}).toBuffer();
 const form=new FormData();form.append('file',new Blob([new Uint8Array(photo)],{type:'image/jpeg'}),'test.jpg');
 const response=await fetch(base+'/api/v1'+admin+'/files',{method:'POST',headers:{authorization:'Bearer '+tokens[0],'idempotency-key':randomUUID()},body:form});const upload=await response.json();assert.equal(response.status,201,JSON.stringify(upload));checked++;
 const file=upload.data;await request(1,'GET',f+'/files/'+file.fileId,undefined,404,randomUUID(),'NOT_FOUND');
 const before=await request(0,'GET',admin+'/dishes/'+dish.id,undefined);await request(0,'PATCH',admin+'/dishes/'+dish.id,{expectedVersion:before.version,imageFileId:file.fileId});
 const refreshed=await request(1,'GET',f+'/files/'+file.fileId,undefined);const image=await fetch(refreshed.url);assert.equal(image.status,200);const meta=await sharp(Buffer.from(await image.arrayBuffer())).metadata();assert.equal(meta.exif,undefined);checked++;
 const tampered=new URL(refreshed.url);tampered.searchParams.set('signature','0'.repeat(64));assert.equal((await fetch(tampered)).status,403);checked++;
 const sharedImageDish=await request(0,'POST',admin+'/dishes',{...dishBody,name:'共享图片菜',imageFileId:file.fileId},201);
 const session=await db.mealSession.create({data:{familyId:family.id,serviceDate:new Date(new Date(Date.now()+28800000).toISOString().slice(0,10)),mealType:'LUNCH'}});
 const available=await request(1,'GET',f+'/dishes?sessionId='+session.id,undefined);assert.ok(available.items.some((d:any)=>d.id===dish.id));
 const temporary=await db.transaction(async tx=>{
  const ctx=await app.get(AccessService).requireMember(tx,{userId:users[0].id,familyId:family.id,requestId:randomUUID()},true,true);
  return app.get(DishService).create(tx,ctx,{...dishBody,name:'临时菜'},session.id);
 });assert.equal(temporary.kind,'TEMPORARY');checked++;
 const promoted=await request(0,'POST',admin+'/dishes/'+temporary.id+'/promote',{expectedVersion:temporary.version});assert.equal(promoted.kind,'PERMANENT');assert.equal(promoted.originSessionId,session.id);
 await request(0,'POST',admin+'/dishes/'+temporary.id+'/promote',{expectedVersion:promoted.version},409,randomUUID(),'TEMPORARY_ONLY');
 await request(0,'DELETE',admin+'/dishes/'+temporary.id+'?expectedVersion='+promoted.version,undefined);
 assert.equal(await db.dish.findUnique({where:{id:temporary.id}}),null);assert.equal(await db.dishVariant.count({where:{dishId:temporary.id}}),0);checked++;
 const untouchedDish=await request(0,'POST',admin+'/dishes',{...dishBody,name:'临时菜'},201);
 const history=await db.familyMenuItem.create({data:{familyId:family.id,sessionId:session.id,dishId:dish.id,variantId:dish.variants[0].id,dishName:dish.name,variantName:dish.variants[0].name,portionDescription:dish.variants[0].portionDescription,dishKind:'PERMANENT',decision:'CONFIRMED',plannedQuantity:1,reason:'',reviewedDemandVersion:1,lastReviewedParticipantCount:1}});
 const pendingHistory=await db.familyMenuItem.create({data:{familyId:family.id,sessionId:session.id,dishId:dish.id,variantId:variant.id,dishName:dish.name,variantName:'微辣',portionDescription:'一份',dishKind:'PERMANENT'}});
 const submitted=await db.personalMenu.create({data:{familyId:family.id,sessionId:session.id,memberId:family.memberId,note:'测试历史备注',submittedAt:new Date()}});
 const orderItem=await db.personalMenuItem.create({data:{familyId:family.id,personalMenuId:submitted.id,familyMenuItemId:history.id,variantId:dish.variants[0].id,dishName:dish.name,variantName:dish.variants[0].name,portionDescription:dish.variants[0].portionDescription,note:'测试点单备注'}});
 const cart=await db.cart.create({data:{familyId:family.id,sessionId:session.id,memberId:family.memberId}});
 await db.cartItem.create({data:{familyId:family.id,cartId:cart.id,variantId:dish.variants[0].id,note:'测试购物车备注'}});
 await db.cartItem.create({data:{familyId:family.id,cartId:cart.id,variantId:untouchedDish.variants[0].id,note:'保留项'}});
 const toRemove=await request(0,'GET',admin+'/dishes/'+dish.id,undefined);
 const preview=await request(0,'GET',admin+'/dishes/'+dish.id+'/deletion-preview',undefined);
 assert.equal(preview.expectedVersion,toRemove.version);assert.equal(preview.cartItemCount,1);assert.equal(preview.submittedItemCount,1);assert.equal(preview.menuItemCount,2);assert.equal(preview.pendingReviewItemCount,1);assert.equal(preview.confirmedItemCount,1);checked++;
 await request(0,'DELETE',admin+'/dishes/'+dish.id+'?expectedVersion='+(toRemove.version-1),undefined,409,randomUUID(),'VERSION_CONFLICT');
 assert.equal(await db.cartItem.count({where:{cartId:cart.id}}),2);
 const deleteKey=randomUUID();await request(0,'DELETE',admin+'/dishes/'+dish.id+'?expectedVersion='+toRemove.version,undefined,200,deleteKey);
 await request(0,'DELETE',admin+'/dishes/'+dish.id+'?expectedVersion='+toRemove.version,undefined,200,deleteKey);
 assert.equal(await db.dish.findUnique({where:{id:dish.id}}),null);
 assert.equal(await db.dishVariant.count({where:{dishId:dish.id}}),0);
 assert.equal(await db.cartItem.count({where:{cartId:cart.id}}),1);
 assert.equal((await db.cartItem.findFirstOrThrow({where:{cartId:cart.id}})).variantId,untouchedDish.variants[0].id);
 assert.equal((await db.cart.findUniqueOrThrow({where:{id:cart.id}})).version,2);
 assert.deepEqual(await db.familyMenuItem.findUnique({where:{id:history.id}}).then(row=>({dishId:row?.dishId,variantId:row?.variantId,dishName:row?.dishName,decision:row?.decision})),{dishId:dish.id,variantId:dish.variants[0].id,dishName:dish.name,decision:'CONFIRMED'});
 assert.equal((await db.personalMenuItem.findUniqueOrThrow({where:{id:orderItem.id}})).note,'测试点单备注');
 assert.ok((await db.menuOperation.findFirstOrThrow({where:{familyId:family.id,action:'DISH_DELETE',resourceId:dish.id}})).summary.includes(dish.name));checked++;
 await request(0,'POST',admin+'/files/'+file.fileId+'/cleanup',undefined,409,randomUUID(),'VALIDATION_ERROR');
 const sharedBefore=await request(0,'GET',admin+'/dishes/'+sharedImageDish.id,undefined);
 await request(0,'DELETE',admin+'/dishes/'+sharedImageDish.id+'?expectedVersion='+sharedBefore.version,undefined);
 const cleanupCandidates=await request(0,'GET',admin+'/files/cleanup-candidates',undefined);
 assert.ok(cleanupCandidates.items.some((item:any)=>item.fileId===file.fileId&&item.canCleanup));
 const asset=await db.fileAsset.findUniqueOrThrow({where:{id:file.fileId}});
 assert.ok(existsSync(resolve(process.env.FILE_STORAGE_ROOT!,asset.storageKey)));
 const cleanupKey=randomUUID(),cleanup=await request(0,'POST',admin+'/files/'+file.fileId+'/cleanup',undefined,202,cleanupKey);
 assert.equal((await request(0,'GET',admin+'/file-cleanup-tasks/'+cleanup.taskId,undefined)).status,'COMPLETED');
 assert.equal(await db.fileAsset.findUnique({where:{id:file.fileId}}),null);
 assert.equal(existsSync(resolve(process.env.FILE_STORAGE_ROOT!,asset.storageKey)),false);
 assert.equal((await request(0,'POST',admin+'/files/'+file.fileId+'/cleanup',undefined,202,cleanupKey)).taskId,cleanup.taskId);
 assert.equal(await db.menuOperation.count({where:{familyId:family.id,action:'FILE_CLEANUP_COMPLETE',resourceId:file.fileId}}),1);checked++;
 const resumedAsset=await db.fileAsset.create({data:{familyId:family.id,uploaderMemberId:family.memberId,storageKey:randomUUID(),mimeType:'image/jpeg',sizeBytes:1,sha256:'0'.repeat(64)}});
 const pendingCleanup=await db.fileCleanupTask.create({data:{familyId:family.id,fileId:resumedAsset.id,storageKey:resumedAsset.storageKey,requestedByMemberId:family.memberId,requestedByName:'测试成员',status:'PENDING'}});
 assert.equal((await request(0,'GET',admin+'/files/cleanup-candidates',undefined)).items.find((item:any)=>item.fileId===resumedAsset.id)?.taskId,pendingCleanup.id);
 const untouchedBefore=await request(0,'GET',admin+'/dishes/'+untouchedDish.id,undefined);
 await request(0,'PATCH',admin+'/dishes/'+untouchedDish.id,{expectedVersion:untouchedBefore.version,imageFileId:resumedAsset.id},409,randomUUID(),'VALIDATION_ERROR');
 await db.fileCleanupTask.update({where:{id:pendingCleanup.id},data:{status:'OBJECT_DELETED'}});
 assert.equal((await request(0,'POST',admin+'/files/'+resumedAsset.id+'/cleanup',undefined,202)).taskId,pendingCleanup.id);
 assert.equal((await request(0,'GET',admin+'/file-cleanup-tasks/'+pendingCleanup.id,undefined)).status,'COMPLETED');
 assert.equal(await db.fileAsset.findUnique({where:{id:resumedAsset.id}}),null);checked++;
 assert.equal(await db.menuOperation.count({where:{familyId:family.id,action:'DISH_DELETE',resourceId:dish.id}}),1);
 const historicPersonal=await request(0,'GET',f+'/meal-sessions/'+session.id+'/personal-menu',undefined);
 assert.equal(historicPersonal.items[0].dishName,dish.name);assert.equal(historicPersonal.items[0].note,'测试点单备注');assert.equal(historicPersonal.items[0].dishDeleted,true);
 const historicMenu=await request(0,'GET',f+'/meal-sessions/'+session.id+'/menu',undefined);
 assert.equal(historicMenu.dishes.find((row:any)=>row.dishId===dish.id)?.dishDeleted,true);
 const historicReview=await request(0,'GET',admin+'/meal-sessions/'+session.id+'/review',undefined);
 assert.equal(historicReview.dishes.find((row:any)=>row.dishId===dish.id)?.dishDeleted,true);
 assert.equal((await request(0,'GET',f+'/meal-sessions/'+session.id+'/cart',undefined)).items[0].variantId,untouchedDish.variants[0].id);checked++;
 await request(0,'POST',admin+'/meal-sessions/'+session.id+'/review',{expectedReviewVersion:historicReview.session.reviewVersion,items:[{itemId:pendingHistory.id,decision:'CONFIRMED',plannedQuantity:1,reason:''}]});
 assert.equal((await db.familyMenuItem.findUniqueOrThrow({where:{id:pendingHistory.id}})).decision,'CONFIRMED');
 const appended=await request(0,'POST',f+'/meal-sessions/'+session.id+'/personal-menu/items',{variantIds:[untouchedDish.variants[0].id],expectedVersion:1});
 assert.ok(appended.items.some((item:any)=>item.variantId===dish.variants[0].id));
 assert.ok(appended.items.some((item:any)=>item.variantId===untouchedDish.variants[0].id&&item.dishDeleted===false));checked++;
 const legacyDeletedAt=new Date();
 const legacy=await db.dish.create({data:{familyId:family.id,name:'历史已删除菜',normalizedName:'历史已删除菜',activeNameKey:null,description:'',imageFileId:null,isAvailable:false,kind:'PERMANENT',deletedAt:legacyDeletedAt,version:3}});
 await db.dishVariant.create({data:{familyId:family.id,dishId:legacy.id,name:'旧规格',normalizedName:'旧规格',activeNameKey:null,portionDescription:'一份',description:'',isAvailable:false,deletedAt:legacyDeletedAt}});
 const deletedList=await request(0,'GET',admin+'/dishes?onlyDeleted=true',undefined);
 assert.ok(deletedList.items.some((row:any)=>row.id===legacy.id));
 await request(0,'DELETE',admin+'/dishes/'+legacy.id+'?expectedVersion=3',undefined);
 assert.equal(await db.dish.findUnique({where:{id:legacy.id}}),null);checked++;
 const incomplete=await request(0,'POST',admin+'/dishes',{...dishBody,name:'缺失快照菜'},201);
 const incompleteHistory=await db.familyMenuItem.create({data:{familyId:family.id,sessionId:session.id,dishId:incomplete.id,variantId:incomplete.variants[0].id,dishName:incomplete.name,variantName:incomplete.variants[0].name,portionDescription:' ',dishKind:'PERMANENT'}});
 await request(4,'DELETE','/families/'+other.id+'/admin/dishes/'+incomplete.id+'?expectedVersion=1',undefined,404,randomUUID(),'NOT_FOUND');
 await request(0,'DELETE',admin+'/dishes/'+incomplete.id+'?expectedVersion=1',undefined,409,randomUUID(),'VALIDATION_ERROR');
 assert.ok(await db.dish.findUnique({where:{id:incomplete.id}}));assert.equal(await db.dishVariant.count({where:{dishId:incomplete.id}}),1);
 assert.ok(await db.familyMenuItem.findUnique({where:{id:incompleteHistory.id}}));
 await db.familyMenuItem.update({where:{id:incompleteHistory.id},data:{portionDescription:'一份'}});
 await request(0,'DELETE',admin+'/dishes/'+incomplete.id+'?expectedVersion=1',undefined);
 assert.ok(await db.familyMenuItem.findUnique({where:{id:incompleteHistory.id}}));checked++;
 const concurrencyKey=randomUUID();const concurrent=await Promise.all(Array.from({length:4},()=>fetch(base+'/api/v1'+admin+'/invites',{method:'POST',headers:{authorization:'Bearer '+tokens[0],'idempotency-key':concurrencyKey,'content-type':'application/json'},body:JSON.stringify({role:'GUEST'})})));
 assert.ok(concurrent.some(r=>r.status===201));assert.ok(concurrent.every(r=>r.status===201||r.status===409));assert.equal(await db.idempotencyRecord.count({where:{userId:users[0].id,key:concurrencyKey}}),1);checked++;
 await request(0,'PATCH',admin+'/members/'+joined.family.memberId,{role:'ADMIN'});
 const leaves=await Promise.all([0,1].map(i=>fetch(base+'/api/v1'+f+'/members/me',{method:'DELETE',headers:{authorization:'Bearer '+tokens[i],'idempotency-key':randomUUID()}})));
 assert.deepEqual(leaves.map(r=>r.status).sort(),[200,409]);assert.equal(await db.familyMember.count({where:{familyId:family.id,role:'ADMIN',status:'ACTIVE'}}),1);checked++;
 console.log(JSON.stringify({status:'PASS',checks:checked,run,db:'127.0.0.1:3317/family_meals_base_test',http:base,fixtures:'retained in isolated test DB; no existing data deleted',limitations:['real WeChat login not run','real COS and notification delivery not run']},null,2));
}finally{await app.close();}
