import 'reflect-metadata';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes, randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { parse } from 'dotenv';
import { JwtService } from '@nestjs/jwt';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module.js';
import { PrismaService } from '../src/database/prisma.service.js';
import { configureApp } from '../src/common/configure-app.js';
import { operations } from '../src/common/contract.js';
import { shanghaiDate } from '../src/family-menu/domain.js';

const env=parse(readFileSync(process.argv[2])),url=new URL(env.DATABASE_URL);
if(url.hostname!=='127.0.0.1'||url.port!=='3317'||url.pathname!=='/family_meals_base_test')throw new Error('Refusing non-isolated database');
process.env.DATABASE_URL=env.DATABASE_URL;
process.env.JWT_SECRET=randomBytes(48).toString('base64');
process.env.IDEMPOTENCY_ENCRYPTION_KEY=randomBytes(32).toString('base64');
process.env.FILE_SIGNING_KEY=randomBytes(48).toString('base64');
const run=randomUUID();process.env.FILE_STORAGE_ROOT=resolve('.local','menu-assets',run);
const app=await NestFactory.create(AppModule,{logger:false});await configureApp(app);
const db=app.get(PrismaService),jwt=new JwtService();let requests=0;const cases:string[]=[];
try {
 await app.listen(process.argv.includes('--serve')?3017:0,'127.0.0.1');
 const base=await app.getUrl();process.env.FILE_PUBLIC_BASE_URL=base;
 const users=await Promise.all(Array.from({length:6},(_,i)=>db.user.create({data:{wechatAppId:run,openid:'menu-'+i,displayName:'验收成员'+i}})));
 const tokens=await Promise.all(users.map(u=>jwt.signAsync({sub:u.id},{secret:process.env.JWT_SECRET,expiresIn:7200,algorithm:'HS256'})));
 let familyId='',sessionId='';
 async function req(user:number,id:string,body?:unknown,params:Record<string,string>={},query:Record<string,unknown>={},expected?:number|number[],key:string=randomUUID()) {
  const op=operations.get(id)!;const p={familyId,sessionId,...params};
  const path=op.path.replace(/\{(\w+)\}/g,(_,k)=>p[k as keyof typeof p]);
  const search=new URLSearchParams(Object.entries(query).map(([k,v])=>[k,String(v)]));
  const r=await fetch(base+'/api/v1'+path+(search.size?'?'+search:''),{method:op.method.toUpperCase(),headers:{authorization:'Bearer '+tokens[user],'idempotency-key':key,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});
  const value=await r.json();requests++;
  const statuses=Array.isArray(expected)?expected:[expected??Number(Object.keys(op.spec.responses).find(k=>k.startsWith('2')))];
  assert.ok(statuses.includes(r.status),id+' '+r.status+' '+JSON.stringify(value));
  assert.ok(value.requestId);return r.ok?value.data:value.error;
 }
 const bootstrap=await db.family.create({data:{name:'Test bootstrap '+run}});
 for(const i of [0,5])await db.familyMember.create({data:{familyId:bootstrap.id,userId:users[i].id,role:'ADMIN',status:'ACTIVE',joinedAt:new Date('2000-01-01')}});
 const family=await req(0,'createFamily',{name:'菜单验收 '+run});familyId=family.id;
 const invite=await req(0,'createInvite',{role:'MEMBER'});
 for(let i=1;i<6;i++)await req(i,'redeemInvite',{code:invite.code});
 // Avatar HTTP regression: real multipart, JWT scope, database persistence and signed asset access.
 const sharp=(await import('sharp')).default;
 const avatarBytes=await sharp({create:{width:32,height:32,channels:3,background:'#eac'}}).png().toBuffer();
 const avatarKey=randomUUID();
 async function uploadAvatar(token:string|undefined,key:string){
  const form=new FormData();form.append('file',new Blob([new Uint8Array(avatarBytes)],{type:'image/png'}),'avatar.png');
  const response=await fetch(base+'/api/v1/me/avatar',{method:'POST',headers:{...(token?{authorization:'Bearer '+token}:{}),'idempotency-key':key},body:form});requests++;
  return {status:response.status,body:await response.json()};
 }
 assert.equal((await uploadAvatar(undefined,randomUUID())).status,401);
 const uploaded=await uploadAvatar(tokens[1],avatarKey);assert.equal(uploaded.status,200);assert.equal(uploaded.body.data.id,users[1].id);
 const replay=await uploadAvatar(tokens[1],avatarKey);assert.equal(replay.status,200);assert.deepEqual(replay.body.data,uploaded.body.data);
 const me=await req(1,'getMe');assert.equal(me.avatar.fileId,uploaded.body.data.avatar.fileId);
 assert.equal((await req(2,'getMe')).avatar,null);
 const roster=await req(2,'listFamilyMembers');assert.ok(roster.items.some((m:any)=>m.avatar?.fileId===me.avatar.fileId));
 const image=await fetch(me.avatar.url);requests++;assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/jpeg');
 assert.equal((await sharp(Buffer.from(await image.arrayBuffer())).metadata()).format,'jpeg');
 const tampered=new URL(me.avatar.url);tampered.searchParams.set('signature','0'.repeat(64));assert.equal((await fetch(tampered)).status,403);requests++;
 cases.push('avatar authenticated multipart, idempotent replay, own-user DB persistence, member visibility, signed image and tamper rejection');
 const today=shanghaiDate(new Date());const session=await req(0,'ensureSession',{serviceDate:today,mealType:'DINNER'});sessionId=session.id;
 assert.equal((await req(0,'ensureSession',{serviceDate:today,mealType:'DINNER'})).id,sessionId);
 assert.equal((await req(1,'listSessions',undefined,{}, {serviceDate:today})).length,1);
 const dishBody={name:'红烧肉',description:'验收',imageFileId:null,isAvailable:true,variants:[{name:'普通',portionDescription:'两人份',description:'',isAvailable:true},{name:'少油',portionDescription:'两人份',description:'',isAvailable:true}]};
 const dish=await req(0,'createDish',dishBody),[a,b]=dish.variants.map((v:any)=>v.id);
 const baseline=(await req(0,'getSession')).reviewVersion;
 assert.equal((await req(2,'submitMenu',{variantIds:[a,'missing'],note:''},{},{},409)).code,'VARIANT_UNAVAILABLE');
 assert.equal(await req(2,'getPersonalMenu'),null);
 assert.equal((await req(0,'getSession')).reviewVersion,baseline);
 assert.equal(await db.familyMenuItem.count({where:{sessionId}}),0);
 const cart=await req(1,'addCartItem',undefined,{variantId:a});
 assert.equal((await req(1,'addCartItem',undefined,{variantId:a})).version,cart.version);
 assert.equal((await req(1,'removeCartItem',undefined,{variantId:a})).items.length,0);
 await req(1,'addCartItem',undefined,{variantId:a});
 const submitKey=randomUUID(),body={variantIds:[a,b],note:'PRIVATE-NOTE'};
 const first=await req(1,'submitMenu',body,{}, {},undefined,submitKey);
 assert.deepEqual(await req(1,'submitMenu',body,{}, {},undefined,submitKey),first);
 assert.equal((await req(1,'submitMenu',body,{}, {},409)).code,'ALREADY_SUBMITTED');
 assert.equal((await req(1,'getCart')).items.length,0);
 await req(1,'addCartItem',undefined,{variantId:b});
 await req(1,'removeCartItem',undefined,{variantId:b});
 assert.equal((await req(1,'getSession')).canAppend,true);
 assert.equal((await req(1,'getSession')).canSubmit,false);
 cases.push('cart set semantics, submit replay, duplicate rejection and atomic cart clearing');
 await req(0,'updateDish',{expectedVersion:dish.version,name:'红烧肉改名'},{dishId:dish.id});
 await Promise.all([req(2,'submitMenu',{variantIds:[a],note:''}),req(3,'submitMenu',{variantIds:[a],note:''}),req(4,'submitMenu',{variantIds:[b],note:''})]);
 let review=await req(0,'getReview');const counts=review.dishes[0];
 assert.equal(counts.uniqueParticipantCount,4);assert.deepEqual(counts.variants.map((v:any)=>v.participantCount).sort(),[2,3]);
 assert.equal(counts.name,'红烧肉');
 assert.equal((await req(2,'getPersonalMenu')).items[0].dishName,'红烧肉');
 const pub=await req(1,'getFamilyMenu');assert.ok(!JSON.stringify(pub).includes('PRIVATE-NOTE'));assert.ok(!JSON.stringify(pub).includes('participants'));
 assert.equal((await req(1,'getReview',undefined,{}, {},403)).code,'FORBIDDEN');
 cases.push('four-person union 3/2/4, private notes and admin-only review');
 cases.push('invalid submission writes nothing; catalog edits preserve first family and personal snapshots');
 const changes=review.dishes.flatMap((d:any)=>d.variants.map((v:any)=>({itemId:v.itemId,decision:'CONFIRMED',plannedQuantity:1.5,reason:''})));
 const beforeBatches=await db.reviewBatch.count({where:{sessionId}});
 await req(0,'reviewMenu',{expectedReviewVersion:review.session.reviewVersion,items:[changes[0],{...changes[1],itemId:'missing'}]}, {},{},404);
 assert.equal(await db.reviewBatch.count({where:{sessionId}}),beforeBatches);
 assert.ok((await req(0,'getReview')).dishes[0].variants.every((v:any)=>v.decision==='UNREVIEWED'));
 const reviewKey=randomUUID(),reviewBody={expectedReviewVersion:review.session.reviewVersion,items:changes};
 const approved=await req(0,'reviewMenu',reviewBody,{}, {},undefined,reviewKey);
 assert.deepEqual(await req(0,'reviewMenu',reviewBody,{}, {},undefined,reviewKey),approved);
 assert.equal(approved.notificationRecordCount,4);
 assert.equal(approved.review.hasTemporaryAdditions,false);
 assert.equal((await req(0,'reviewMenu',reviewBody,{}, {},409)).code,'REVIEW_VERSION_CONFLICT');
 assert.equal(await db.reviewBatch.count({where:{sessionId}}),beforeBatches+1);
 cases.push('atomic batch failure rollback, fractional portions, review replay and stale version rejection');
 await req(5,'submitMenu',{variantIds:[a],note:'晚到成员'});
 review=await req(0,'getReview');const late=review.dishes[0].variants.find((v:any)=>v.variantId===a);
 assert.equal(late.decision,'CONFIRMED');assert.equal(late.needsReview,true);assert.equal(late.participantCount-late.lastReviewedParticipantCount,1);
 assert.equal(review.hasTemporaryAdditions,true);
 const temp=await req(0,'createTemporaryDish',{...dishBody,name:'临时加菜',variants:[dishBody.variants[0]]});
 review=await req(0,'getReview');const tempRow=review.dishes.find((d:any)=>d.dishId===temp.id);
 assert.equal(tempRow.kind,'TEMPORARY');assert.equal(tempRow.uniqueParticipantCount,0);assert.equal(tempRow.variants[0].needsReview,true);
 assert.equal(review.hasTemporaryAdditions,true);
 await req(0,'submitMenu',{variantIds:[temp.variants[0].id],note:'掌勺补充点餐'});
 review=await req(0,'getReview');
 const pending=review.dishes.flatMap((d:any)=>d.variants.filter((v:any)=>v.needsReview).map((v:any)=>({itemId:v.itemId,decision:'CONFIRMED',plannedQuantity:2,reason:''})));
 const raceBody={expectedReviewVersion:review.session.reviewVersion,items:pending};
 const race=await Promise.all([req(0,'reviewMenu',raceBody,{}, {},[200,409]),req(0,'reviewMenu',raceBody,{}, {},[200,409])]);
 assert.equal(race.filter(r=>r.batchId).length,1);
 assert.equal(race.filter(r=>r.code==='REVIEW_VERSION_CONFLICT').length,1);
 assert.equal(await db.reviewBatch.count({where:{sessionId}}),beforeBatches+2);
 assert.ok((await req(0,'getReview')).dishes.every((d:any)=>d.variants.every((v:any)=>!v.needsReview)));
 cases.push('late participant retains decision and needs review, zero-demand temporary dish, admin submission, concurrent review single winner');
 const note=await req(1,'updateNote',{note:'updated PRIVATE-NOTE',expectedVersion:first.version});
 assert.equal(note.version,2);assert.equal((await req(1,'updateNote',{note:'bad',expectedVersion:1},{},{},409)).code,'VERSION_CONFLICT');
 assert.equal((await req(1,'updateNote',{note:note.note,expectedVersion:2})).version,2);
 assert.ok((await req(1,'getPersonalMenu')).items.every((i:any)=>!i.needsReview));
 assert.equal((await req(0,'getReview')).hasTemporaryAdditions,false);
 await req(0,'createTemporaryDish',{...dishBody,name:'跨设备零需求追加',variants:[dishBody.variants[0]]});
 const coldReview=await req(0,'getReview');
 assert.equal(coldReview.hasTemporaryAdditions,true);
 assert.equal(coldReview.dishes.find((d:any)=>d.name==='跨设备零需求追加').uniqueParticipantCount,0);
 cases.push('server addition marker survives cold clients and distinguishes note-only changes from zero-demand additions');
 const notifications=await req(1,'listMyNotifications',undefined,{}, {page:1,pageSize:100});
 assert.ok(notifications.items.length>=2);assert.ok(notifications.items.every((n:any)=>n.status==='SKIPPED'&&n.reasonCode==='CHANNEL_DISABLED'));
 assert.equal((await req(1,'getNotificationConfig')).enabled,false);
 await req(1,'recordSubscriptionResult',{templateId:'test-template',result:'ACCEPT'});
 const audit=await req(0,'listOperations',undefined,{}, {sessionId,pageSize:100});assert.equal(audit.items.filter((i:any)=>i.action==='MENU_REVIEW').length,2);
 cases.push('legacy note optimistic locking without re-review, durable audit, truthful disabled notification records');
 const other=await req(5,'createFamily',{name:'隔离家庭 '+run});
 await req(5,'getSession',undefined,{familyId:other.id},{},404);
 const yesterday=new Date(today);yesterday.setUTCDate(yesterday.getUTCDate()-1);
 const historical=await db.mealSession.create({data:{familyId,serviceDate:yesterday,mealType:'DINNER'}});
 assert.equal((await req(0,'getSession',undefined,{sessionId:historical.id})).submitBlockedReason,'DATE_READ_ONLY');
 assert.equal((await req(0,'submitMenu',{variantIds:[a],note:''},{sessionId:historical.id},{},409)).code,'DATE_READ_ONLY');
 cases.push('cross-family isolation and historical read-only enforcement');

 // Execute the shipped mini-program services/transport with a wx.request network
 // adapter, not mocked API responses. Only authentication is a test fixture.
 const require=createRequire(import.meta.url),root=resolve('../miniprogram');
 const config=require(root+'/config.js');config.USE_MOCK=false;config.TRANSPORT_MODE='https';config.BASE_URL=base+'/api/v1';
 (globalThis as any).wx={request:(o:any)=>{fetch(o.url,{method:o.method,headers:o.header,body:o.method==='GET'||o.data===undefined?undefined:JSON.stringify(o.data)}).then(async r=>o.success({statusCode:r.status,data:await r.json()})).catch(o.fail);},showToast(){}};
 const transport=require(root+'/api/transport.js'),services=require(root+'/api/services.js');transport.setToken(tokens[0]);
 assert.equal((await services.getSession(familyId,sessionId)).id,sessionId);
 assert.equal((await services.getFamilyMenu(familyId,sessionId)).dishes.length,3);
 const fresh=await services.ensureSession(familyId,today,'LUNCH');
 assert.equal((await req(0,'addCartItem',undefined,{sessionId:fresh.id,variantId:temp.variants[0].id},{},409)).code,'VARIANT_UNAVAILABLE');
 await services.addCartItem(familyId,fresh.id,a);
 assert.equal((await services.getCart(familyId,fresh.id)).items.length,1);
 await services.submitMenu(familyId,fresh.id,[a],'前端真实请求');
 const frontReview=await services.getReview(familyId,fresh.id);
 await services.reviewMenu(familyId,fresh.id,frontReview.session.reviewVersion,[{itemId:frontReview.dishes[0].variants[0].itemId,decision:'CONFIRMED',plannedQuantity:1,reason:''}]);
 assert.equal((await services.getPersonalMenu(familyId,fresh.id)).items[0].decision,'CONFIRMED');
 cases.push('shipped frontend services and transport -> real HTTP -> MySQL submission and approval');
 // Real HTTP/SQL append regression in the isolated local database only.
 const freshParams={sessionId:fresh.id};
 const personal=await req(1,'submitMenu',{variantIds:[a],note:'member original'},freshParams);
 let r=await req(0,'getReview',undefined,freshParams);
 await req(0,'reviewMenu',{expectedReviewVersion:r.session.reviewVersion,items:[{itemId:r.dishes[0].variants.find((v:any)=>v.variantId===a).itemId,decision:'CONFIRMED',plannedQuantity:3,reason:'preserve'}]},freshParams);
 const before=await req(1,'getFamilyMenu',undefined,freshParams);
 const personalBefore=await req(1,'getPersonalMenu',undefined,freshParams);
 await req(1,'addCartItem',undefined,{...freshParams,variantId:b});
 await req(1,'addCartItem',undefined,{...freshParams,variantId:a});
 const appendBody={variantIds:[b],expectedVersion:personal.version},appendKey=randomUUID();
 // Invalid mixed request must roll back all demand, menu and cart writes.
 await req(1,'appendMenu',{variantIds:[b,'missing'],expectedVersion:personal.version},freshParams,{},409);
 assert.deepEqual(await req(1,'getPersonalMenu',undefined,freshParams),personalBefore);
 const appended=await req(1,'appendMenu',appendBody,freshParams,{},undefined,appendKey);
 assert.deepEqual(await req(1,'appendMenu',appendBody,freshParams,{},undefined,appendKey),appended);
 assert.equal(appended.id,personal.id);assert.equal(appended.submittedAt,personal.submittedAt);assert.equal(appended.note,personal.note);assert.equal(appended.version,2);
 assert.equal(appended.items.length,2);assert.equal(appended.items.find((i:any)=>i.variantId===a).needsReview,false);
 assert.equal(appended.items.find((i:any)=>i.variantId===b).decision,'UNREVIEWED');
 assert.deepEqual((await req(1,'getCart',undefined,freshParams)).items.map((i:any)=>i.variantId),[a]);
 const after=await req(1,'getFamilyMenu',undefined,freshParams);
 assert.deepEqual(after.dishes[0].variants.find((v:any)=>v.variantId===a),before.dishes[0].variants.find((v:any)=>v.variantId===a));
 assert.equal(after.session.reviewVersion,before.session.reviewVersion+1);
 assert.equal((await req(1,'appendMenu',appendBody,freshParams,{},409)).code,'VERSION_CONFLICT');
 assert.equal((await req(1,'updateNote',{note:'stale',expectedVersion:1},freshParams,{},409)).code,'VERSION_CONFLICT');
 r=await req(0,'getReview',undefined,freshParams);assert.equal(r.hasTemporaryAdditions,true);
 const newItem=r.dishes[0].variants.find((v:any)=>v.variantId===b);
 const approval={expectedReviewVersion:r.session.reviewVersion,items:[{itemId:newItem.itemId,decision:'CONFIRMED',plannedQuantity:2,reason:'append approved'}]};
 await req(0,'reviewMenu',{...approval,expectedReviewVersion:before.session.reviewVersion},freshParams,{},409);
 await req(0,'reviewMenu',approval,freshParams);
 assert.ok((await req(1,'getPersonalMenu',undefined,freshParams)).items.every((i:any)=>i.decision==='CONFIRMED'&&!i.needsReview));
 assert.equal((await req(0,'getReview',undefined,freshParams)).hasTemporaryAdditions,false);
 const revision=(await req(0,'getSession',undefined,freshParams)).reviewVersion;
 transport.setToken(tokens[1]);
 await services.appendMenu(familyId,fresh.id,[a,b],2);
 assert.equal((await req(0,'getSession',undefined,freshParams)).reviewVersion,revision);
 // Two stale-equal append versions have exactly one winner, with no duplicate links.
 const extra=await req(0,'createDish',{...dishBody,name:'并发追加',variants:dishBody.variants});
 const raceAppend=await Promise.all(extra.variants.map((v:any)=>req(1,'appendMenu',{variantIds:[v.id],expectedVersion:2},freshParams,{},[200,409])));
 assert.equal(raceAppend.filter((x:any)=>x.id).length,1);assert.equal(raceAppend.filter((x:any)=>x.code==='VERSION_CONFLICT').length,1);
 assert.equal((await req(1,'getPersonalMenu',undefined,freshParams)).items.length,3);
 await req(1,'appendMenu',{variantIds:[a],expectedVersion:1},{sessionId:historical.id},{},409);
 await req(1,'appendMenu',{variantIds:[a],expectedVersion:1},{familyId:other.id,sessionId:fresh.id},{},403);
 await req(1,'getReview',undefined,freshParams,{},403);
 cases.push('same member approved -> append -> second approval; original preserved; duplicate replay; rollback; concurrent append single winner; history and permission isolation');
 { // Item-note regression uses an isolated new family; no existing selections are modified.
 const noteFamily=await req(0,'createFamily',{name:'逐菜备注 '+run});familyId=noteFamily.id;
 const noteInvite=await req(0,'createInvite',{role:'MEMBER'});
 await req(1,'redeemInvite',{code:noteInvite.code});await req(2,'redeemInvite',{code:noteInvite.code});
 sessionId=(await req(0,'ensureSession',{serviceDate:today,mealType:'LUNCH'})).id;
 const nd=await req(0,'createDish',{...dishBody,name:'逐菜备注测试'}),[na,nb]=nd.variants.map((v:any)=>v.id);
 const writeParams={variantId:na},key=randomUUID();
 const draft=await req(1,'updateCartItemNote',{note:'A only',expectedVersion:1},writeParams,{},200,key);
 assert.equal(draft.items[0].note,'A only');
 assert.deepEqual(await req(1,'updateCartItemNote',{note:'A only',expectedVersion:1},writeParams,{},200,key),draft);
 await req(1,'updateCartItemNote',{note:'stale',expectedVersion:1},writeParams,{},409);
 await req(1,'updateCartItemNote',{note:'B only',expectedVersion:draft.version},{variantId:nb});
 let own=await req(1,'submitMenu',{variantIds:[na,nb],note:''});
 assert.equal(own.items.find((i:any)=>i.variantId===na).note,'A only');assert.equal(own.items.find((i:any)=>i.variantId===nb).note,'B only');
 assert.equal((await req(1,'getCart')).items.length,0);
 await req(2,'submitMenu',{variantIds:[na],note:''});
 let review=await req(0,'getReview');
 await req(0,'reviewMenu',{expectedReviewVersion:review.session.reviewVersion,items:review.dishes[0].variants.map((v:any)=>({itemId:v.itemId,decision:'CONFIRMED',plannedQuantity:2,reason:'keep'}))});
 const publicBefore=await req(2,'getFamilyMenu'), batches=await db.reviewBatch.count({where:{sessionId}});
 const updateBody={note:'changed after review',expectedVersion:own.version},noteKey=randomUUID();
 own=await req(1,'updatePersonalItemNote',updateBody,writeParams,{},200,noteKey);
 assert.deepEqual(await req(1,'updatePersonalItemNote',updateBody,writeParams,{},200,noteKey),own);
 assert.ok(own.items.every((i:any)=>i.decision==='CONFIRMED'&&!i.needsReview&&i.plannedQuantity===2&&i.reason==='keep'));
 assert.equal(own.items.find((i:any)=>i.variantId===nb).note,'B only');
 assert.equal((await req(2,'getPersonalMenu')).items[0].note,'');
 review=await req(0,'getReview');assert.equal(review.hasNoteUpdates,true);assert.equal(review.hasTemporaryAdditions,false);
 const participants=review.dishes[0].variants.find((v:any)=>v.variantId===na).participants;
 assert.equal(participants.filter((p:any)=>p.noteUpdatedAfterReview).length,1);assert.ok(participants.some((p:any)=>p.note==='changed after review'&&p.noteUpdatedAt));
 assert.deepEqual((await req(2,'getFamilyMenu')).dishes,publicBefore.dishes);
 assert.equal(await db.reviewBatch.count({where:{sessionId}}),batches);
 const stable=(await req(0,'getSession')).reviewVersion;
 assert.equal((await req(1,'updatePersonalItemNote',{note:'changed after review',expectedVersion:own.version},writeParams)).version,own.version);
 assert.equal((await req(0,'getSession')).reviewVersion,stable);
 await req(1,'updatePersonalItemNote',{note:'stale',expectedVersion:1},writeParams,{},409);
 await req(2,'updatePersonalItemNote',{note:'not mine',expectedVersion:1},{variantId:nb},{},404);
 await req(1,'updatePersonalItemNote',{note:'cross family',expectedVersion:own.version},{familyId:other.id,variantId:na},{},403);
 await req(1,'updatePersonalItemNote',{note:'x'.repeat(501),expectedVersion:own.version},writeParams,{},400);
 own=await req(1,'updatePersonalItemNote',{note:'',expectedVersion:own.version},writeParams);
 assert.equal(own.items.find((i:any)=>i.variantId===na).note,'');assert.equal(own.items.find((i:any)=>i.variantId===na).noteUpdatedAfterReview,true);
 const extraNoteDish=await req(0,'createDish',{...dishBody,name:'追加备注菜'}),nc=extraNoteDish.variants[0].id;
 const newCart=await req(1,'getCart');await req(1,'updateCartItemNote',{note:'append only',expectedVersion:newCart.version},{variantId:nc});
 own=await req(1,'appendMenu',{variantIds:[nc],expectedVersion:own.version});
 assert.equal(own.items.find((i:any)=>i.variantId===nc).note,'append only');assert.equal(own.items.find((i:any)=>i.variantId===nb).note,'B only');
 assert.equal(own.items.find((i:any)=>i.variantId===na).decision,'CONFIRMED');assert.equal(own.items.find((i:any)=>i.variantId===na).needsReview,false);
 const raceNotes=await Promise.all([na,nb].map(variantId=>req(1,'updatePersonalItemNote',{note:'race',expectedVersion:own.version},{variantId},{},[200,409])));
 assert.equal(raceNotes.filter((r:any)=>r.id).length,1);assert.equal(raceNotes.filter((r:any)=>r.code==='VERSION_CONFLICT').length,1);
 const oldMeal=await db.mealSession.create({data:{familyId,serviceDate:yesterday,mealType:'LUNCH'}});
 await req(1,'updatePersonalItemNote',{note:'past',expectedVersion:1},{sessionId:oldMeal.id,variantId:na},{},409);
 await req(1,'updateCartItemNote',{note:'past',expectedVersion:1},{sessionId:oldMeal.id,variantId:na},{},409);
 const nextSession=(await req(0,'ensureSession',{serviceDate:today,mealType:'DINNER'})).id;
 assert.equal((await req(1,'submitMenu',{variantIds:[na],note:''},{sessionId:nextSession})).items[0].note,'');
 cases.push('per-item draft persistence, submit and append, reviewed note reminder without re-review, owner/family/session isolation, clearing, no-op/idempotency, optimistic race, date and length validation');
 }
 const report={status:'PASS',run,requests,cases,db:'127.0.0.1:3317/family_meals_base_test',http:base,limitations:['authentication uses isolated fixture JWT; real WeChat code2Session not tested','notification provider disabled; no messages sent','fixtures retained; no existing data deleted']};
 mkdirSync(resolve('../integration/results'),{recursive:true});writeFileSync(resolve('../integration/results/menu-http-acceptance.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 if(process.argv.includes('--serve')){
  mkdirSync('.local',{recursive:true});writeFileSync('.local/menu-preview.json',JSON.stringify({base,family,session,tokens,users:users.map(u=>({id:u.id,displayName:u.displayName}))}));
  console.log('Test API retained on loopback 3017; fixture credentials stored only in ignored .local/menu-preview.json');
  await new Promise<void>(resolve=>{process.once('SIGINT',resolve);process.once('SIGTERM',resolve);});
 }
} finally {await app.close();}
